# Generated by Django 3.2.16 on 2023-04-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_usersettings_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundColour',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
