# Generated by Django 3.2.16 on 2023-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_auto_20230405_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='address',
            new_name='d_address',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='city',
            new_name='d_city',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='country',
            new_name='d_country',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='county',
            new_name='d_county',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone_number',
            new_name='d_phone_number',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='postcode',
            new_name='d_postcode',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='d_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='d_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
