# Generated by Django 3.2 on 2023-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
