# Generated by Django 3.2 on 2023-04-14 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_pricing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
