# Generated by Django 3.2 on 2023-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_pricing_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['-created'], name='catalogue_p_created_0ebde3_idx'),
        ),
    ]
