# Generated by Django 3.2 on 2023-04-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20230415_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.pricing'),
        ),
    ]
