# Generated by Django 3.2 on 2023-04-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_product_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pricing',
            new_name='catagory',
        ),
    ]
