# Generated by Django 3.2 on 2023-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_rename_pricing_product_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory_name',
            field=models.CharField(default='some name', max_length=200),
        ),
    ]
