# Generated by Django 3.2.16 on 2023-04-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_usersetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
