# Generated by Django 3.2 on 2023-04-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('promo_image', models.ImageField(default='default.jpg', upload_to='promo_images/')),
                ('description', models.TextField(default='description')),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200)),
                ('product_image', models.ImageField(default='default.jpg', upload_to='product_images/')),
                ('description', models.TextField(default='description')),
                ('created', models.DateField(auto_now_add=True)),
                ('catagory_name', models.CharField(default='uncatagorised', max_length=200)),
                ('catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.pricing')),
                ('favourite', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['-created'], name='catalogue_p_created_0ebde3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='catalogue_p_created_500242_idx'),
        ),
    ]
