# Generated by Django 3.2 on 2023-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20230419_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='promo_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
