# Generated by Django 3.2.16 on 2023-01-31 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('listedtime', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_seller_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-listedtime'],
            },
        ),
        migrations.AddIndex(
            model_name='createlisting',
            index=models.Index(fields=['-listedtime'], name='store_creat_listedt_ef4bbb_idx'),
        ),
    ]
