# Generated by Django 3.2.16 on 2023-02-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createlisting',
            old_name='seller',
            new_name='sellerID',
        ),
        migrations.RemoveField(
            model_name='createlisting',
            name='created',
        ),
        migrations.AddField(
            model_name='createlisting',
            name='catagory',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Homeware'), (2, 'Electronics'), (3, 'Entertainment'), (4, 'Clothing'), (5, 'Toys'), (6, 'Health')], default=1),
        ),
        migrations.AddField(
            model_name='createlisting',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Like New'), (3, 'Used'), (4, 'None Functional')], default=3),
        ),
        migrations.AddField(
            model_name='createlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='createlisting',
            name='listedtime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
