# Generated by Django 3.2.16 on 2023-02-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230209_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlisting',
            name='stock',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Avalible'), (2, 'Sold')], default=1),
        ),
    ]
