# Generated by Django 3.2.16 on 2023-03-11 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_createlisting_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateListing',
            new_name='Listing',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='store_creat_listedt_ef4bbb_idx',
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-listedtime'], name='store_listi_listedt_0cd7f4_idx'),
        ),
    ]
