# Generated by Django 3.2.16 on 2023-03-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_listing_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='product_image',
            field=models.ImageField(default='default.jpg', upload_to='media/product_images/'),
        ),
    ]
