# Generated by Django 3.2.16 on 2023-03-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20230314_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favourite',
            field=models.PositiveSmallIntegerField(choices=[(1, 'saved'), (2, 'Notsaved')], default=2),
        ),
    ]
