# Generated by Django 3.2.16 on 2023-03-18 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_auto_20230316_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='favourite',
        ),
        migrations.AddField(
            model_name='listing',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
