# Generated by Django 3.2.16 on 2023-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20230318_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='catagory',
            field=models.CharField(choices=[('Homeware', 'Homeware'), ('Electronics', 'Electronics'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Toys', 'Toys'), ('Health', 'Health')], default='Homeware', max_length=13),
        ),
    ]
