# Generated by Django 3.2.16 on 2023-03-19 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0016_auto_20230318_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='favourites',
        ),
        migrations.AddField(
            model_name='listing',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
