# Generated by Django 4.2 on 2023-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('product_image', models.ImageField(default='default.jpg', upload_to='product_images/')),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('catagory', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='catalog_pro_created_b92f5e_idx'),
        ),
    ]
