# Generated by Django 3.2 on 2023-04-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='promo_image',
            field=models.ImageField(default='default.jpg', upload_to='promo_images/'),
        ),
    ]
