# Generated by Django 3.2 on 2023-04-14 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('d_last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('d_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('d_address', models.CharField(blank=True, max_length=150, null=True)),
                ('d_city', models.CharField(blank=True, max_length=40, null=True)),
                ('d_county', models.CharField(blank=True, max_length=80, null=True)),
                ('d_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('d_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
